--host --url $HOST
--login --username admin@$DOMAIN --password Eiswein87!
--registration --email jenn@augustwenty.com  --pass pass1234 --api_access true --role admin --self_service_storage {'role':'admin'}
--registration --email meri.kullberg@augustwenty.com --pass pass1234 --api_access true --role admin --self_service_storage {'role':'admin'}
