--host --url $HOST
--login --username admin@$DOMAIN --password Eiswein87!
--registration --email user1@nxdomain.com  --pass 123123123 --api_access true --role admin --self_service_storage {'role':'admin'}
--registration --email user2@nxdomain.com --pass 123123123 --api_access true --role admin --self_service_storage {'role':'admin'}
